esphome:
  name: schuur-sensor-esp
  friendly_name: Schuur sensor esp

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "gn+l9/KoDjegYhnqLAqaJBDjMaw0Rv6xh0qc6gQrGjs="

ota:
  - platform: esphome
    password: "d5a9fe81842450848670a7b28776c332"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Schuur-Sensor-Esp"
    password: "fd7SlLSBYrQw"

captive_portal:

web_server:

sensor:
  - platform: dht
    pin: GPIO21
    model: DHT11
    temperature:
      name: "Temperatuur Schuur"
    humidity:
      name: "Vochtigheidsgraad Schuur"
    update_interval: 60s

  - platform: internal_temperature
    name: "ESP32 module temperatuur"

binary_sensor:
  - platform: gpio
    pin: GPIO27
    name: "PIR Sensor"
    device_class: motion

output:
  - platform: ledc
    pin: GPIO19
    id: status_led_output

light:
  - platform: monochromatic
    name: "Status Led"
    output: status_led_output
    default_transition_length: 1s
    gamma_correct: 2.8
   