esphome:
  name: schuur-temp-humi-move
  friendly_name: schuur temp humi move


esp32:
  board: esp32dev

logger:

api:

ota:
  platform: esphome
  

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "schuur-temp-humi-move Fallback"
    password: "fallback1234"

captive_portal:

web_server:

sensor:
  - platform: dht
    pin: GPIO21
    model: DHT11
    temperature:
      name: "Temperatuur Schuur"
    humidity:
      name: "Vochtigheidsgraad Schuur"
    update_interval: 60s

binary_sensor:
  - platform: gpio
    pin: GPIO27
    name: "PIR Schuur"
    device_class: motion