esphome:
  name: temp-humi-zolder
  friendly_name: Temp & Humi Zolder

esp32:
  board: esp32dev

logger:

api:
  encryption:
    key: !secret api_key

ota:
  platform: esphome
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "temp-humi-zolder"
    password: "fallback1234"

captive_portal:

web_server:


sensor:
  - platform: dht
    pin: GPIO2
    model: DHT11
    temperature:
      name: "Temperatuur Zolder"
    humidity:
      name: "Vochtigheidsgraad Zolder"
    update_interval: 60s

  - platform: internal_temperature
    name: "ESP32 module temperatuur"

binary_sensor:
  - platform: gpio
    pin: GPIO27
    name: "PIR Sensor"
    device_class: motion

output:
  - platform: ledc
    pin: GPIO19
    id: status_led_output

light:
  - platform: monochromatic
    name: "Status Led"
    output: status_led_output
    default_transition_length: 1s
    gamma_correct: 2.8
  