esphome:
  name: temp-humid-veranda
  friendly_name: Temp & Humid Veranda

esp32:
  board: esp32dev

logger:

api:

ota:
  platform: esphome
  

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "temp-humid-esp32 Fallback"
    password: "fallback1234"

captive_portal:

web_server:

sensor:
  - platform: dht
    pin: GPIO21
    model: DHT11
    temperature:
      name: "Temperatuur Veranda"
    humidity:
      name: "Vochtigheidsgraad Veranda"
    update_interval: 60s

binary_sensor:
  - platform: gpio
    pin: GPIO27
    name: "PIR Veranda"
    device_class: motion

    