sensor:
  - name: "Huidig Tarief"
    unique_id: huidig_tarief
    state: "{{ states('sensor.zonneplan_current_electricity_tariff')|float(0) }}"
    unit_of_measurement: "€/kWh"
    icon: mdi:currency-eur
    
  - name: "All-in Tarief"
    unique_id: all_in_tarief
    state: >
      {% set base_price = states('sensor.zonneplan_current_electricity_tariff')|float(0) %}
      {% set tax = 0.11 %}  # Elektriciteitsbelasting en ODE
      {% set vat = 0.21 %}  # BTW
      {{ (base_price * (1 + vat) + tax)|round(4) }}
    unit_of_measurement: "€/kWh"
    icon: mdi:currency-eur
    
  - name: "Vergelijking met Gemiddeld"
    unique_id: vergelijking_met_gemiddeld
    state: >
      {% set current = states('sensor.zonneplan_current_electricity_tariff')|float(0) %}
      {% set avg_sensors = [
        'sensor.zonneplan_forecast_tariff_hour_1',
        'sensor.zonneplan_forecast_tariff_hour_2',
        'sensor.zonneplan_forecast_tariff_hour_3',
        'sensor.zonneplan_forecast_tariff_hour_4',
        'sensor.zonneplan_forecast_tariff_hour_5',
        'sensor.zonneplan_forecast_tariff_hour_6',
        'sensor.zonneplan_forecast_tariff_hour_7',
        'sensor.zonneplan_forecast_tariff_hour_8'
      ] %}
      
      {% set sum = 0 %}
      {% set count = 0 %}
      {% for sensor in avg_sensors %}
        {% if states(sensor) != 'unknown' %}
          {% set sum = sum + states(sensor)|float(0) %}
          {% set count = count + 1 %}
        {% endif %}
      {% endfor %}
      
      {% if count > 0 %}
        {% set avg = sum / count %}
        {% set diff = ((current - avg) / avg * 100)|round(1) %}
        {% if diff > 0 %}
          {{ diff }}% duurder dan gemiddeld
        {% elif diff < 0 %}
          {{ diff|abs }}% goedkoper dan gemiddeld
        {% else %}
          Gelijk aan gemiddeld
        {% endif %}
      {% else %}
        Niet beschikbaar
      {% endif %}
    icon: mdi:chart-line-variant
    
  - name: "Minimum Vandaag"
    unique_id: minimum_vandaag
    state: >
      {% set prices = [] %}
      {% set forecast_sensors = [
        'sensor.zonneplan_forecast_tariff_hour_1',
        'sensor.zonneplan_forecast_tariff_hour_2',
        'sensor.zonneplan_forecast_tariff_hour_3',
        'sensor.zonneplan_forecast_tariff_hour_4',
        'sensor.zonneplan_forecast_tariff_hour_5',
        'sensor.zonneplan_forecast_tariff_hour_6',
        'sensor.zonneplan_forecast_tariff_hour_7',
        'sensor.zonneplan_forecast_tariff_hour_8'
      ] %}
      
      {% set current = states('sensor.zonneplan_current_electricity_tariff')|float(0) %}
      {% set prices = [current] %}
      
      {% for sensor in forecast_sensors %}
        {% if states(sensor) != 'unknown' %}
          {% set prices = prices + [states(sensor)|float(0)] %}
        {% endif %}
      {% endfor %}
      
      {% if prices|length > 0 %}
        {{ prices|min|round(4) }}
      {% else %}
        Niet beschikbaar
      {% endif %}
    unit_of_measurement: "€/kWh"
    icon: mdi:arrow-down-bold
    
  - name: "Maximum Vandaag"
    unique_id: maximum_vandaag
    state: >
      {% set prices = [] %}
      {% set forecast_sensors = [
        'sensor.zonneplan_forecast_tariff_hour_1',
        'sensor.zonneplan_forecast_tariff_hour_2',
        'sensor.zonneplan_forecast_tariff_hour_3',
        'sensor.zonneplan_forecast_tariff_hour_4',
        'sensor.zonneplan_forecast_tariff_hour_5',
        'sensor.zonneplan_forecast_tariff_hour_6',
        'sensor.zonneplan_forecast_tariff_hour_7',
        'sensor.zonneplan_forecast_tariff_hour_8'
      ] %}
      
      {% set current = states('sensor.zonneplan_current_electricity_tariff')|float(0) %}
      {% set prices = [current] %}
      
      {% for sensor in forecast_sensors %}
        {% if states(sensor) != 'unknown' %}
          {% set prices = prices + [states(sensor)|float(0)] %}
        {% endif %}
      {% endfor %}
      
      {% if prices|length > 0 %}
        {{ prices|max|round(4) }}
      {% else %}
        Niet beschikbaar
      {% endif %}
    unit_of_measurement: "€/kWh"
    icon: mdi:arrow-up-bold
    
  - name: "Gemiddeld Vandaag"
    unique_id: gemiddeld_vandaag
    state: >
      {% set prices = [] %}
      {% set forecast_sensors = [
        'sensor.zonneplan_forecast_tariff_hour_1',
        'sensor.zonneplan_forecast_tariff_hour_2',
        'sensor.zonneplan_forecast_tariff_hour_3',
        'sensor.zonneplan_forecast_tariff_hour_4',
        'sensor.zonneplan_forecast_tariff_hour_5',
        'sensor.zonneplan_forecast_tariff_hour_6',
        'sensor.zonneplan_forecast_tariff_hour_7',
        'sensor.zonneplan_forecast_tariff_hour_8'
      ] %}
      
      {% set current = states('sensor.zonneplan_current_electricity_tariff')|float(0) %}
      {% set prices = [current] %}
      
      {% for sensor in forecast_sensors %}
        {% if states(sensor) != 'unknown' %}
          {% set prices = prices + [states(sensor)|float(0)] %}
        {% endif %}
      {% endfor %}
      
      {% if prices|length > 0 %}
        {# Bereken gemiddelde #}
        {% set sum = 0 %}
        {% for price in prices %}
          {% set sum = sum + price %}
        {% endfor %}
        {{ (sum / prices|length)|round(4) }}
      {% else %}
        Niet beschikbaar
      {% endif %}
    unit_of_measurement: "€/kWh"
    icon: mdi:calculator