esphome:
  name: tuindeur
  friendly_name: tuindeur 

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "FJPogXKyLVyqLxFJcuIpHyIgYd44hZGZYFFdN9iso5s="

ota:
  - platform: esphome
    password: "d8be80c5f36f28bd6dd5bdfd92e95f25"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: 192.168.2.107
    gateway: 192.168.2.1
    subnet: 255.255.255.0
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Tuindeur Fallback Hotspot"
    password: "I6JipmyVW1QA"

captive_portal:

web_server:

sensor:
  - platform: dht
    pin: GPIO21
    model: DHT11
    temperature:
      name: "Temperatuur tuindeur"
    humidity:
      name: "Vochtigheidsgraad tuindeur"
    update_interval: 60s

  - platform: internal_temperature
    name: "ESP32 module temperatuur"

binary_sensor:
  - platform: gpio
    pin: GPIO27
    name: "PIR Sensor"
    device_class: motion

output:
  - platform: ledc
    pin: GPIO19
    id: status_led_output

light:
  - platform: monochromatic
    name: "Status Led"
    output: status_led_output
    default_transition_length: 1s
    gamma_correct: 2.8
   
    